apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: developers-cluster-2
  namespace: argocd
spec:
  description: Developer workloads for leaf-2 (cluster3)
  sourceRepos:
    - https://github.com/ably77/agw-federated-cluster-2.git
  destinations:
    - namespace: wgu-demo
      server: '*'
    - namespace: wgu-demo-frontend
      server: '*'
    - namespace: agentgateway-system
      server: '*'
    - namespace: monitoring
      server: '*'
  clusterResourceWhitelist:
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
