apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - enrollment-chatbot.yaml
  - data-product-api.yaml
  - financial-aid-mcp.yaml
  - graph-db-mock.yaml
  - abac-ext-authz.yaml
